// Evidence catalogue. categories: PHYSICAL DIGITAL TESTIMONY DOCUMENT FINANCIAL TIMELINE
// importance: KEY | HIGH | MEDIUM | LOW.   `hidden` is only revealed once the item is linked on the Evidence Board.
export const evidence = [
  { id:'E01', title:'Stopped Regulator Clock', category:'PHYSICAL', importance:'HIGH', location:'Workshop', related:[], timeline:'T11',
    description:'The wall regulator above the bench. Pendulum still, hands fixed at 11:47.',
    hidden:'The hands say one thing. The mechanism behind them will say another.' },
  { id:'E02', title:'Strike Count Wheel', category:'PHYSICAL', importance:'KEY', location:'Workshop', related:[], timeline:'T06',
    description:'Behind the dial, the count-wheel lever rests in the notch for TEN strikes. The clock last struck ten. It never struck eleven.',
    hidden:'The clock stopped between 10:00 and 11:00. Someone moved the hands afterwards.' },
  { id:'E03', title:'Empty Weight Cord', category:'PHYSICAL', importance:'MEDIUM', location:'Workshop', related:[], timeline:'T06',
    description:'The tall-case clock is missing its brass driving weight. The cord dangles, freshly detached.',
    hidden:'The missing weight is heavy enough to kill. Where did it go?' },
  { id:'E04', title:'Napkin-Wrapped Brass Weight', category:'PHYSICAL', importance:'KEY', location:'Workshop', related:['helena'], timeline:'T06',
    description:'The missing weight, scrubbed clean and wrapped in a cream napkin with a gold crest. Hidden under the bench cupboard. Faint traces remain in the threading.',
    hidden:'The gold crest belongs to the Hotel Meridian gala dining room. The killer came from the gala.' },
  { id:'E05', title:'Preliminary Medical Note', category:'DOCUMENT', importance:'MEDIUM', location:'Workshop', related:[], timeline:'T12',
    description:'Dr. Salt: one heavy blow to the back of the skull. Time of death between 10:00 PM and midnight. Estimate unreliable: the workshop radiators were running at full heat.',
    hidden:'A wide window. It cannot settle the time on its own.' },
  { id:'E06', title:'Edmund’s Phone — Last Message', category:'DIGITAL', importance:'HIGH', location:'Workshop', related:['marianne','helena'], timeline:'T07',
    description:'10:48 PM, to Marianne: “Regrettably, I must cancel breakfast. I will be working late. Please do not wait up.” Every earlier message from Edmund is lowercase with no punctuation.',
    hidden:'Edmund never wrote like this. Someone else typed it on his phone at 10:48.' },
  { id:'E07', title:'Edmund’s Phone — Call Log', category:'DIGITAL', importance:'HIGH', location:'Workshop', related:['julian'], timeline:'T05',
    description:'Incoming call, 10:32 PM, Julian Roche. Answered. Duration 2 min 14 sec. Nothing after it.',
    hidden:'Julian talked to Edmund at 10:32, so Edmund was alive then, and Julian lied about it.' },
  { id:'E08', title:'Fenwick Trust Ledger', category:'FINANCIAL', importance:'KEY', location:'Office', related:['helena'], timeline:'',
    description:'Four payments totalling $240,000 to “H.A. Consulting Ltd”, approved by H. Ashworth alone. Edmund’s scanned signature has been pasted in. Pencilled in the margin: “Ask H.A. before the trustees meet.”',
    hidden:'Helena had a motive worth killing for: Edmund had found the theft.' },
  { id:'E09', title:'Harrow Foundation Gala Program', category:'DOCUMENT', importance:'MEDIUM', location:'Office', related:['helena'], timeline:'T10',
    description:'Edmund’s invitation to the gala at the Hotel Meridian. Closing remarks by H. Ashworth: 11:45 PM.',
    hidden:'Helena’s speech at 11:45 is very close to the 11:47 on the clock.' },
  { id:'E10', title:'Valet Stub — Ashworth', category:'TIMELINE', importance:'KEY', location:'Hotel Meridian', related:['helena'], timeline:'T03',
    description:'Valet record for H. Ashworth’s silver sedan: OUT 10:12 PM. IN 11:24 PM. Seventy-two minutes away from the gala.',
    hidden:'Helena’s alibi has a hole exactly where the murder happened.' },
  { id:'E11', title:'Entrance Camera Log', category:'DIGITAL', importance:'HIGH', location:'Shop front', related:['marianne','tobias','helena'], timeline:'T04',
    description:'10:04 Marianne leaves. 10:15 a figure in a long coat and umbrella enters. 10:56 the same figure leaves carrying a bag. 11:05 Tobias slips out the side door.',
    hidden:'Marianne and Tobias left outside the killing window. The umbrella figure did not.' },
  { id:'E12', title:'Kessler Letter of Intent', category:'DOCUMENT', importance:'MEDIUM', location:'Office', related:['marianne'], timeline:'T01',
    description:'A signed intent to sell Vale & Sons to the Kessler Group. The shop would close. The family name would come off the door.',
    hidden:'A motive for Marianne. But motive is not opportunity.' },
  { id:'E13', title:'Forged Provenance Certificate', category:'DOCUMENT', importance:'MEDIUM', location:'Office', related:['julian'], timeline:'T05',
    description:'A certificate of origin for an 1840s regulator. Edmund’s note: “Not genuine. J.R. — confront Friday.”',
    hidden:'Julian had a reason to lie to us. Lying is not the same as killing.' },
  { id:'E14', title:'Pawn Slip — T. Wren', category:'FINANCIAL', importance:'LOW', location:'Workshop', related:['tobias'], timeline:'',
    description:'Three clock movements pawned over four months, signed T. Wren. Found in his coat pocket.',
    hidden:'A theft, and a reason for Tobias to lie about the night. Not a reason to kill.' },
  { id:'E15', title:'Two Cups', category:'PHYSICAL', importance:'LOW', location:'Workshop', related:[], timeline:'T03',
    description:'Two cups on the bench. One has cold coffee in it. The other is clean, with an unopened teabag beside it.',
    hidden:'Edmund was expecting a guest, and it was someone he had time for.' },
  { id:'E16', title:'Marianne: The Argument', category:'TESTIMONY', importance:'MEDIUM', location:'Interview', related:['marianne'], timeline:'T01',
    description:'Marianne was there 9:40–10:04. They argued about the sale. Edmund was alive when she left. He said he had “a late appointment about the trust.”',
    hidden:'Edmund was alive at 10:04, and someone else was coming.' },
  { id:'E17', title:'Marianne: “Dad Never Writes Like That”', category:'TESTIMONY', importance:'HIGH', location:'Interview', related:['marianne'], timeline:'T07',
    description:'Marianne says the 10:48 message was wrong: capital letters, full stops, the word “regrettably”. That is why she came back at midnight.',
    hidden:'The 10:48 message is not evidence that Edmund was alive at 10:48.' },
  { id:'E18', title:'Julian: The 10:32 Call', category:'TESTIMONY', importance:'KEY', location:'Interview', related:['julian','helena'], timeline:'T05',
    description:'Julian says Edmund answered, sounded tense, and said: “Helena’s here, about the accounts. I’ll call you back.” He never did.',
    hidden:'At 10:32 Edmund was alive, and Helena was standing in his workshop.' },
  { id:'E19', title:'Julian: Corvin’s Bar Tab', category:'FINANCIAL', importance:'MEDIUM', location:'Interview', related:['julian'], timeline:'T05',
    description:'A bar tab from Corvin’s on Alder Street: opened 10:05 PM, closed 11:40 PM, four whiskies. The bartender knows him well.',
    hidden:'Julian was across the river the whole time Edmund was being killed.' },
  { id:'E20', title:'Tobias: The Thud', category:'TESTIMONY', importance:'KEY', location:'Interview', related:['tobias'], timeline:'T06',
    description:'From the basement, about twenty to eleven: a calm, low second voice, then a heavy thud, then running water. And the ticking of the wall regulator stopped. It never stops.',
    hidden:'The regulator stopped at about 10:40, an hour before the time it shows.' },
  { id:'E21', title:'Helena: “The Moment He Died”', category:'TESTIMONY', importance:'KEY', location:'Interview', related:['helena'], timeline:'T11',
    description:'Helena said she was on stage “at the very moment poor Edmund died”. She knew the clock time, which police told no one. She says Marianne told her.',
    hidden:'Only the killer, or someone the killer told, could have known 11:47.' },
  { id:'E22', title:'Taxi Receipt — Marianne', category:'FINANCIAL', importance:'LOW', location:'Interview', related:['marianne'], timeline:'T02',
    description:'A cab receipt: pickup Harrow Street, 10:06 PM. Payment by Marianne’s card.',
    hidden:'Marianne was in a taxi while Edmund still had 34 minutes to live.' },
  { id:'E23', title:'Founders’ Photograph', category:'DOCUMENT', importance:'LOW', location:'Office', related:['helena','julian'], timeline:'',
    description:'Ten years ago. Edmund, Helena and Julian outside the Fenwick Trust’s first office, holding scissors and a ribbon.',
    hidden:'All three were trustees. The ledger has three names on it; only one of them is on the bad payments.' },
  { id:'E24', title:'Police Briefing: Clock Time Withheld', category:'TESTIMONY', importance:'HIGH', location:'Workshop', related:[], timeline:'T12',
    description:'Inspector Rourke: “The wall regulator stopped at 11:47. Nobody outside this room knows that. Not the press. Not the family. Not the suspects.”',
    hidden:'Anyone who mentions 11:47 without being told has explaining to do.' },
  { id:'E25', title:'Marianne: “I Told No One”', category:'TESTIMONY', importance:'KEY', location:'Interview', related:['marianne','helena'], timeline:'T11',
    description:'Marianne says she told nobody about the clock, only the police, and she never spoke to Helena that night.',
    hidden:'Helena lied about how she learned the time on the clock.' },
];
