// Interrogation scripts. question: {id,text,requires:[evidence],after:[questionIds],response:[lines],mood,reveals:[evidence],suspicion:±n}
export const interrogations = {
  marianne: { set:'interrogation', questions:[
    { id:'m1', text:'Where were you tonight?', mood:'guarded', suspicion:8,
      response:['At home. I went to bed early.','…I could not sleep. So around midnight I came by the shop. To check on him.'] },
    { id:'m2', text:'Tell me about your father and the shop.', mood:'sad', suspicion:0,
      response:['Vale & Sons is a hundred and thirty years old. It is all he ever loved.','Some days I think he loved it more than me. Some days I think that is why I stayed.'] },
    { id:'m3', text:'Your father was selling to the Kessler Group. Did you know?', requires:['E12'], mood:'angry', suspicion:15,
      response:['He told me tonight.','…That is the first I heard of it. Thirty years of that place and he told me over tea.'] },
    { id:'m4', text:'You said you were home. The camera shows you leaving the shop at 10:04.', requires:['E11'], after:['m1'], mood:'broken', suspicion:-5, reveals:['E16','E22'],
      response:['Yes. All right. I was there. We argued about the sale.','I told him he would sell it over my dead body. Or his. I cannot remember which. I hate that I said it.','I left at ten. Took a cab, here is the receipt. He was fine. He was alive and furious and he told me he had “a late appointment about the trust”. That is all I know.'] },
    { id:'m5', text:'Your father texted you at 10:48. Does it sound like him?', requires:['E06'], mood:'calm', suspicion:-5, reveals:['E17'],
      response:['No. Never. Capital letters and full stops? He writes like a telegram, if he writes at all.','“Regrettably.” Nobody says that. That is why I came back at midnight. I knew something was wrong.'] },
    { id:'m6', text:'Did you tell anyone the time on the wall clock?', requires:['E21'], mood:'calm', suspicion:-10, reveals:['E25'],
      response:['I did not tell anyone. I could not even say it out loud.','I told the police. And nobody else. I never spoke to Helena tonight. Why?'] },
  ] },

  julian: { set:'interrogation', questions:[
    { id:'j1', text:'Where were you tonight?', mood:'wry', suspicion:0,
      response:['Corvin’s Bar, on Alder Street. From about ten. I drank alone, if you must know.','Do not look so pleased. It is a very ordinary tragedy.'] },
    { id:'j2', text:'When did you last speak to Edmund?', mood:'wry', suspicion:12, after:['j1'],
      response:['Wednesday. We had lunch. Nothing since. He was in fine spirits.'] },
    { id:'j3', text:'Your number is in his call log: 10:32 PM, two minutes.', requires:['E07'], after:['j2'], mood:'nervous', suspicion:12,
      response:['A pocket call. He kept me on speed-dial. He is… he was absent-minded with phones.','Do not write that down as a lie, please. Write it as a misunderstanding.'] },
    { id:'j4', text:'You lied about the call. Edmund found this forged certificate. He was going to confront you on Friday.', requires:['E07','E13'], after:['j3'], mood:'broken', suspicion:20, reveals:['E18'],
      response:['…Three certificates. Three. I needed the money. He would have ruined me on Friday.','So yes. I rang him at 10:32 to beg for more time. He answered. He said, quite quietly: “Helena’s here, about the accounts. I’ll call you back.”','He never did. I did not kill him, Detective. I heard the last calm sentence he ever spoke, and I said nothing to anyone, because saying it meant explaining why I rang.'] },
    { id:'j5', text:'Can anyone confirm you were at Corvin’s?', after:['j4'], mood:'wry', suspicion:-25, reveals:['E19'],
      response:['The bartender. And my tab: opened at 10:05, closed at 11:40. Four whiskies. Take it. I would like it back.'] },
    { id:'j6', text:'You are a Fenwick trustee. Explain “H.A. Consulting”.', requires:['E08'], mood:'cold', suspicion:-10,
      response:['I have never seen that name. Helena kept the books. We all trusted her. God.','Do you know what it is to realise you are the only honest fool in a room full of very clever people?'] },
    { id:'j7', text:'Tell me about the three of you. You, Edmund and Helena.', requires:['E23'], mood:'sad', suspicion:0,
      response:['Founding trustees. Edmund was the conscience. Helena was the brains. I was the charm.','I always assumed I was the most useless of the three. Turns out I was the most transparent.'] },
  ] },

  tobias: { set:'interrogation', questions:[
    { id:'t1', text:'When did you leave the shop tonight?', mood:'nervous', suspicion:6,
      response:['N-nine thirty. Mr. Vale sent me home early. He said he had things to do.'] },
    { id:'t2', text:'Where do you work in the shop?', mood:'nervous', suspicion:0,
      response:['The basement bench. Right under the workshop. You can hear everything through the boards: Mr. Vale pacing, the regulator ticking. Three years I have gone to sleep to that sound.'] },
    { id:'t3', text:'The camera shows you leaving by the side door at 11:05.', requires:['E11'], after:['t1'], mood:'broken', suspicion:10,
      response:['…Oh. Oh no. I was there. I was downstairs. I panicked, I thought— I did not do anything. Please.'] },
    { id:'t4', text:'What did you hear from the workshop tonight?', after:['t3'], mood:'nervous', suspicion:-15, reveals:['E20'],
      response:['Marianne first, shouting. Then quiet. Then somebody else. Low and calm, like a client.','About twenty to eleven, a thud. A heavy one. Then water running for a long while.','And the tick stopped. In three years that regulator has never stopped. I noticed it before I noticed anything else.'] },
    { id:'t5', text:'Why did you pawn three clock movements?', requires:['E14'], mood:'broken', suspicion:5,
      response:['My mother’s care home costs more than I earn. I was going to buy them back. Please do not tell the guild.','I would never touch Mr. Vale. He was the only person who ever gave me a chance.'] },
    { id:'t6', text:'Why didn’t you go up after the thud?', after:['t4'], mood:'nervous', suspicion:-5,
      response:['I thought it was a row. I stayed hidden until eleven. When I went up the workshop light was off. I saw nothing. I ran.','I should have gone up. I will think about that until I die.'] },
  ] },

  helena: { set:'interrogation', questions:[
    { id:'h1', text:'Where were you tonight?', mood:'calm', suspicion:0,
      response:['At the Harrow Foundation Gala, at the Hotel Meridian. I gave the closing remarks at 11:45.','Six hundred people watched me do it. I was speaking at the very moment poor Edmund died. I find that hard to forgive myself for.'] },
    { id:'h2', text:'You said “the very moment he died”. The time on that clock was never released.', requires:['E24'], after:['h1'], mood:'nervous', suspicion:22, reveals:['E21'],
      response:['I… Marianne mentioned it. When she telephoned. She was distraught. I assumed the clock was the time.','Forgive me. A long night, and a longer week. I am choosing my words poorly.'] },
    { id:'h3', text:'Tell me about Edmund and the Fenwick Trust.', after:['h1'], mood:'calm', suspicion:0,
      response:['Edmund was the conscience of Fenwick. We audited every year and he was exacting. It is a good trust. It has done real good for this city.','If I had to point you anywhere, I would say look at Julian. He was desperate. Everyone could see it.'] },
    { id:'h4', text:'The ledger shows $240,000 to “H.A. Consulting”. Approved by you alone.', requires:['E08'], after:['h3'], mood:'cold', suspicion:25,
      response:['A consultancy retainer. Approved by the board. Edmund had questions. I intended to answer them at the next meeting.','I would be careful with that word, Detective. “Alone.” Trusts are complicated things.'] },
    { id:'h5', text:'Your car left the Meridian at 10:12 PM and returned at 11:24.', requires:['E10'], after:['h1'], mood:'cold', suspicion:25,
      response:['A client emergency. I fetched documents from my office.','Which client? That is privileged. I am sure you understand.'] },
    { id:'h6', text:'Julian says Edmund told him, at 10:32, that you were with him.', requires:['E18'], after:['h5'], mood:'cold', suspicion:20,
      response:['Julian Roche is a forger and a drunk with every reason to lie. Believe him at your peril.','I do not care to be spoken about in this manner.'] },
    { id:'h7', text:'The weapon was wrapped in a Meridian gala napkin. Only the gala dining room uses that crest.', requires:['E04','E10'], after:['h5'], mood:'broken', suspicion:40,
      response:['…You cannot possibly— Those napkins are on six hundred laps.','Edmund would have ruined me. Twenty years of my work, gone, over a spreadsheet. He would not even let me explain.','I would like my lawyer, Detective. Ironically, I know a very good one.'] },
  ] },
};
