// Locations and their tappable objects. x/y are percentages of the scene.
// object: { id,label,icon,x,y,text, evidence:[], requires:[], lockedText, puzzle, doneText }
export const locations = [
  { id:'workshop', name:'The Workshop', tag:'CRIME SCENE', set:'workshop', image:'workshop.webp',
    blurb:'Where Edmund died. Two hundred clocks, and one that has stopped.',
    objects:[
      { id:'body', label:'Edmund', icon:'◉', x:46, y:74, evidence:['E05'],
        text:'Face-down beside the bench. One blow to the back of the head; nothing else disturbed, no sign of a struggle. Dr. Salt gives you a preliminary note: a wide window, and a warning about the heat.' },
      { id:'regulator', label:'Wall clock', icon:'◷', x:68, y:24, evidence:['E01'],
        text:'The wall regulator: pendulum still, both hands stopped at 11:47. Every other clock in the room is running. This is the time everyone will talk about.' },
      { id:'movement', label:'Clock movement', icon:'⚙', x:80, y:38, requires:['E01'], puzzle:'P1',
        lockedText:'Nothing draws your eye. You have not looked at the clock itself yet.',
        text:'Behind the dial, the movement’s striking train is exposed. A clockmaker would read the story here. Can you?', doneText:'You have read the count wheel. The clock last struck ten.' },
      { id:'tallcase', label:'Tall-case clock', icon:'▮', x:16, y:46, evidence:['E03'],
        text:'The long-case clock in the corner. Its case door is open. The brass driving weight is gone; the cord dangles free where it was detached.' },
      { id:'cupboard', label:'Bench cupboard', icon:'▣', x:30, y:78, evidence:['E04'], requires:['E03'],
        lockedText:'Tool cupboards, rags, oil. Nothing that seems to matter.',
        text:'Behind the rags, something heavy wrapped in a cream napkin. A gold crest in the corner. Inside: the missing brass weight, scrubbed clean.' },
      { id:'sink', label:'Bench sink', icon:'◌', x:88, y:64,
        text:'The basin is still damp. Someone washed something here, recently. A thread of pale lint sits in the drain.' },
      { id:'cups', label:'Two cups', icon:'☕', x:58, y:58, evidence:['E15'],
        text:'One cup half full of cold coffee. Beside it, a second cup, clean, with an unopened teabag. Set out for someone who never got to drink.' },
      { id:'coat', label:'Coat hook', icon:'◭', x:92, y:30, evidence:['E14'],
        text:'A young man’s work coat. In the pocket: a pawn slip for three clock movements, signed T. Wren.' },
      { id:'phone', label:'Edmund’s phone', icon:'▯', x:60, y:86, puzzle:'P2',
        text:'A phone lies face-up under the bench, screen locked. Four-digit passcode.', doneText:'Unlocked. You have already read his messages and call log.' },
      { id:'plaque', label:'Brass plaque', icon:'▭', x:44, y:10,
        text:'Above the door, a brass plaque, polished daily: VALE & SONS · HOROLOGISTS · EST. 1887.' },
      { id:'window', label:'Window', icon:'▥', x:8, y:16,
        text:'Rain streaks the glass. The latch is fastened from the inside. Nobody came or went this way.' },
      { id:'shelf', label:'Shelves', icon:'▤', x:92, y:50,
        text:'Two hundred clocks, all ticking out of step with each other. Edmund said a workshop should sound like a conversation.' },
    ] },

  { id:'office', name:'Edmund’s Office', tag:'UPSTAIRS', set:'office', image:'office.webp', intro:'loc_office',
    blurb:'Paperwork, pipe smoke, and the papers Edmund was worried about.',
    objects:[
      { id:'desk', label:'Desk', icon:'▭', x:50, y:60, evidence:['E12'],
        text:'Under the blotter: a signed letter of intent selling Vale & Sons to the Kessler Group. Dated last week. Edmund had told no one until tonight.' },
      { id:'drawer', label:'Desk drawer', icon:'▣', x:34, y:74, evidence:['E13'],
        text:'A certificate of origin for an 1840s regulator, with Edmund’s note across the top: “Not genuine. J.R. — confront Friday.”' },
      { id:'ledger', label:'Trust ledger', icon:'▤', x:82, y:52, puzzle:'P3',
        text:'A green ledger marked FENWICK TRUST. Edmund has pencilled question marks in the margin. Something in here doesn’t reconcile.', doneText:'You found the bad entry. Edmund’s pencil marks make sense now.' },
      { id:'pinboard', label:'Pinboard', icon:'▦', x:16, y:34, evidence:['E09'],
        text:'An invitation pinned beside the calendar: the Harrow Foundation Gala, Hotel Meridian. The program lists the speakers. Closing remarks: H. Ashworth, 11:45 PM.' },
      { id:'photo', label:'Framed photo', icon:'▢', x:66, y:28, evidence:['E23'],
        text:'Ten years ago. Edmund, Helena and Julian in front of the Fenwick Trust’s first office, holding oversized scissors. Founding trustees, all three.' },
      { id:'portrait', label:'Portrait', icon:'▨', x:36, y:26,
        text:'Josiah Vale, founder, scowling in oils. Beneath the frame, a motto carved into brass: TIME KEEPS THE HONEST.' },
      { id:'lamp', label:'Banker’s lamp', icon:'◍', x:70, y:66,
        text:'Still on. Edmund read late in the evening, and never left a lamp burning by accident.' },
    ] },

  { id:'alley', name:'Shop Front & Alley', tag:'STREET LEVEL', set:'alley', image:'alley.webp', intro:'loc_alley',
    blurb:'The security recorder, the side door and the wet pavement.',
    objects:[
      { id:'recorder', label:'Security recorder', icon:'▣', x:24, y:46, puzzle:'P4',
        text:'The entrance camera’s recorder. Four motion clips saved tonight, in the wrong order, timestamps stripped by the power cut. You will have to work out the sequence.', doneText:'Clips sequenced. You have the camera log.' },
      { id:'sidedoor', label:'Side door', icon:'▮', x:76, y:52,
        text:'The apprentice’s door. Deadbolt intact. A smear of clock oil at handle height: someone left in a hurry.' },
      { id:'counter', label:'Appointment book', icon:'▤', x:50, y:72,
        text:'On the counter: Saturday, 2 PM — “Kessler Group walkthrough”. Edmund’s handwriting, underlined twice.' },
      { id:'display', label:'Shop window', icon:'◷', x:50, y:30,
        text:'Every clock in the window shows a different time. A hand-lettered card: “A clock tells you what it wants you to believe.”' },
      { id:'gutter', label:'Gutter', icon:'≋', x:14, y:84,
        text:'The rain has thinned to a drizzle and left puddles. According to the weather feed, it stopped altogether around eleven.' },
    ] },

  { id:'hotel', name:'Hotel Meridian', tag:'GALA', set:'hotel', image:'hotel.webp', intro:'loc_hotel',
    unlock:{ evidence:['E09'] }, hint:'A place you have no reason to visit yet.',
    blurb:'Where the Harrow Foundation Gala is still winding down.',
    objects:[
      { id:'valet', label:'Valet stand', icon:'◈', x:22, y:60, evidence:['E10'], requires:['E09'],
        lockedText:'The valet will not open the records without a reason.',
        text:'The valet keeps a stub for every car. H. Ashworth’s silver sedan: OUT 10:12 PM. IN 11:24 PM.' },
      { id:'stage', label:'Ballroom stage', icon:'▬', x:56, y:38, requires:['E10'], puzzle:'P5',
        lockedText:'A stage, a podium, six hundred chairs. Helena spoke here at 11:45 sharp. Nothing here proves anything yet.',
        text:'Six hundred witnesses saw Helena on this stage at 11:45. Line up the alibis and see who each really covers.', doneText:'You have tested every alibi against the true window.' },
      { id:'napkins', label:'Dining tables', icon:'▦', x:78, y:66, requires:['E04'],
        lockedText:'Tables laid for the gala dinner, cream napkins, gold rims.',
        text:'The gala tables carry the same cream napkins with the same gold crest as the one wrapped around the murder weapon. The hotel confirms: private dinner only.' },
      { id:'coatcheck', label:'Coat check', icon:'◭', x:10, y:32,
        text:'The attendant remembers Ms. Ashworth well. She collected her long coat at 10:11 and returned it at 11:26, hair damp.' },
    ] },
];
